### ISSUE TITLE
Is this dead?

### ISSUE THREAD

**Issue by ben-page** [joyent/nodejs-advisory-board#21]
One meeting date has already been missed (Week of 2014-12-15). Extrapolating, there should have been another meeting this week.

**Comment by voodootikigod** [comment]
Hi @ben-page we did have that meeting, notes are here: https://github.com/joyent/nodejs-advisory-board/blob/master/meetings/2014-12-19/minutes.md

Next meeting information:


Please join our next meeting, Wednesday Jan 14, 2015 at 4:00 PM EST / 1:00 AM PST at
[https://global.gotomeeting.com/join/524998381](https://global.gotomeeting.com/join/524998381) or please dial-in in using your telephone.

```
Please join my meeting from your computer, tablet or smartphone.
https://global.gotomeeting.com/join/524998381

You can also dial in using your phone.
United States (Long distance): +1 (646) 749-3122
Access Code: 524-998-381
More phone numbers: https://global.gotomeeting.com/524998381/numbersdisplay.html


```

**Comment by ben-page** [comment]
Thank you for your response. May I suggest that you update the README.md and http://nodejs.org/advisory-board/? If a person doesn't dig into the repo, it appears that you all stopped meeting.
