### ISSUE TITLE
Clarification question about meeting access

### ISSUE THREAD

**Issue by maxogden** [joyent/nodejs-advisory-board#3]
According to [this version](https://github.com/joyent/node-website/blob/73b618f74730dfca6eb518b8971f2da880615fc3/doc/about/advisory-board/index.md) of the charter, section 4.7: `All project contributors are welcome to observe at Node.js Advisory Board meetings.`

Later under 'Open Governance Principles' it states: `Open Contributions: anyone should be able to participate and contribute.`

Does this mean that all advisory board meetings will be open to anyone? I think the charter needs to be more specific in this regard.

I would personally like to see the advisory board adopt an open communication process by which all meetings are uploaded you youtube and backroom conversations are kept to a minimum.

**Comment by voodootikigod** [comment]
@maxogden could I close this?
