### ISSUE TITLE
Conference Call Details

### ISSUE THREAD

**Issue by Burstaholic** [joyent/nodejs-advisory-board#34]
The phone information posted in the meeting minutes for the last couple of meetings has been incorrect - I was only able to obtain the correct Meeting ID from the GoToMeeting interface.

That's fine, but if that is going to be the only place to find the correct info, outdated info shouldn't be posted/left up in the minutes. That's less critical with additional communications channels coming up, but could still frustrate some people.

**Comment by dshaw** [comment]
@voodootikigod What do you think? Should we update the minutes to point to http://nodeadvisoryboard.com/ for the next meeting info?

**Comment by voodootikigod** [comment]
yes, also would love to use uberconference instead as its much much much
cheaper and I have been paying for it thus far

*Chris Williams*

@voodootikigod <http://twitter.com/voodootikigod> | GitHub
<http://github.com/voodootikigod>

*The things I make that you should check out:*
SaferAging <http://www.saferaging.com/> | JSConf <http://jsconf.com/> |
RobotsConf <http://robotsconf.com/> | RobotsWeekly
<http://robotsweekly.com/>

Help me end the negativity on the internet, share this
<http://jsconf.eu/2011/an_end_to_negativity.html>.

**Comment by voodootikigod** [comment]
Added to all meeting minutes. Gotomeeting discussion will be branched as a new ticket.
